catalog/urls.py
from django.urls import path
from .views import AuthorListView, index, BookListView, BookDetailView, AuthorDetailView

urlpatterns = [
    path('', index, name='index'),
    path('books/', BookListView.as_view(), name='books'),
    path('book/<int:pk>', BookDetailView.as_view(), name='book-detail'),
    path('authors/', AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', AuthorDetailView.as_view(), name='author-detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# Para agregar el sistema de autentificacion

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
import uuid

from django.db import models
from django.urls import reverse

# para implementar los usuarios, importamos
from django.contrib.auth.models import User


# Create your models here.


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(
        max_length=200, help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author is a string rather than an object because it hasn't been declared yet in the file

    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book")

    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    genre = models.ManyToManyField(
        Genre, help_text='Select a genre for this book')

    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title', 'author']

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('book-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    # implementamos el usuario
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

catalog/views.py
import http
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import Book, BookInstance, Author, Genre

# Create your views here.


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(
        status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    # Libros que contienen la palabra "the"

    book_include_the = Book.objects.filter(title__contains='the').count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'book_include_the': book_include_the,
        'num_visits': num_visits
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


"""
class BookListView(ListView):
    model = Book

    # Si no pongo nada más, por defecto esta vista crea el queryset de todos los objetos de Book.
    # Si quiero hacer uno personalizado, puedo generar una funcion get_queryset()

    def get_queryset(self):
        return Book.objects.all()

    # Por defecto, el contexto que se envia al template es el query especificado en el model = Book.
    # Para especificar que quiero mandar en el context, hago lo siguiente

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['algun_valor'] = 'esto es algo que se envia al template como context'
        return context

"""


class BookListView(LoginRequiredMixin, ListView):
    model = Book
    paginate_by = 10


class BookDetailView(DetailView):
    model = Book


class AuthorListView(ListView):
    model = Author
    paginate_by = 10


class AuthorDetailView(DetailView):
    model = Author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.all().order_by('-title')
        return context


"""
La manera larga de escribir la vista de clase ListView es la siguiente

class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'   # your own name for the list as a template variable
    queryset = Book.objects.filter(title__icontains='war')[:5] # Get 5 books containing the title war
    template_name = 'books/my_arbitrary_template_name_list.html'  # Specify your own template name/location
"""


"""
class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, 'home.html', context)
"""

"""
La manera de escribir la vista de clase BookDetailView como función es la siguiente

def book_detail_view(request, primary_key):
    try:
        book = Book.objects.get(pk=primary_key)
    except Book.DoesNotExist:
        raise Http404('book does not exist')
    return render(request, 'book-detail.html', context={'book': book})


Hay otra manera mas corta de hacerlo:

from django.shortcuts import get_object_or_404

def book_detail_view(request, primary_key):
    book = get_object_or_404(Book, pk=primary_key)
    return render(request, 'catalog/book_detail.html', context={'book': book})

        
"""

catalog/templates/base_generic copy.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
                Local Library
            {% endblock title %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
        <!-- Add additional CSS in static file -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="apple-touch-icon"
              sizes="180x180"
              href="{% static 'img/apple-touch-icon.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="32x32"
              href="{% static 'img/favicon-32x32.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="16x16"
              href="{% static 'img/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'img/site.webmanifest' %}">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {% block sidebar %}
                        <ul class="sidebar-nav">
                            <li>
                                <a href="{% url 'index' %}">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'books' %}">All books</a>
                            </li>
                            <li>
                                <a href="{% url 'authors' %}">All authors</a>
                            </li>
                        </ul>
                    {% endblock %}
                </div>
                <div class="col-sm-10 ">
                    {% block content %}{% endblock %}
                    {% block pagination %}
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                    {% endif %}
                                    <span class="page-current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                                    {% if page_obj.has_next %}<a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>{% endif %}
                                </span>
                            </div>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
                Local Library
            {% endblock title %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
        <!-- Add additional CSS in static file -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="apple-touch-icon"
              sizes="180x180"
              href="{% static 'img/apple-touch-icon.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="32x32"
              href="{% static 'img/favicon-32x32.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="16x16"
              href="{% static 'img/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'img/site.webmanifest' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'index' %}">LocalLibrary</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarText"
                        aria-controls="navbarText"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'books' %}">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'authors' %}">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/admin" target='_blank'>Admin</a>
                        </li>
                    </ul>
                    {% if user.is_authenticated %}
                        <a class="nav-link" id="logout" href="{% url 'logout' %}?next={{request.path}}">Logout</a>
                    {% else %}
                        <a class="nav-link" id="login" href="{% url 'login' %}?next={{request.path}}">Login</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-10 ">
                    {% if user.is_authenticated %}<p>Hi {{ user.username }}</p>{% endif %}
                    {% block content %}{% endblock %}
                    {% block pagination %}
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                    {% endif %}
                                    <span class="page-current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                                    {% if page_obj.has_next %}<a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>{% endif %}
                                </span>
                            </div>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
    </body>
</html>

catalog/templates/catalog/author_detail.html
{% extends 'base_generic.html' %}
{% block title %}
    Author Detail
{% endblock title %}
{% block content %}
    <div class='container mt-5'>
        <h1>Author: {{ author }}</h1>
        <p>
            {{ author.date_of_birth }} -
            {% if author.date_of_death != None %}{{ author.date_of_death }}{% endif %}
        </p>
        <div class='container mt-5'>
            <h3>Books</h3>
            {% for book in books %}
                {% if book.author == author %}<h5><a href='{{ book.get_absolute_url }}'>{{ book }}</a></h5>
                <p>{{ book.summary }}</p>
                {% endif %}
                
            {% endfor %}
        </div>
    </div>
    {% for copy in book.bookinstance_set.all %}
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
            {{ copy.get_status_display }}
        </p>
        {% if copy.status != 'a' %}
            <p>
                <strong>Due to be returned:</strong> {{ copy.due_back }}
            </p>
        {% endif %}
        <p>
            <strong>Imprint:</strong> {{ copy.imprint }}
        </p>
        <p class="text-muted">
            <strong>Id:</strong> {{ copy.id }}
        </p>
    {% endfor %}
</div>
{% endblock content %}

catalog/templates/catalog/author_list.html
{% extends 'base_generic.html' %}
{% block title %}
    Author List
{% endblock title %}
{% block content %}
    <div class='container mt-5'>
        <h1>Author List</h1>
        {% if author_list %}
            <ul>
                {% for author in author_list %}
                    <li>
                        <a class='author-name' href='{{ author.get_absolute_url }}'>{{ author }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No hay Autores para mostrar</p>
        {% endif %}
    </div>
    <p>{{ algun_valor }}</p>
{% endblock content %}

catalog/templates/catalog/book_detail.html
{% extends 'base_generic.html' %}
{% block title %}
    Books Detail
{% endblock title %}
{% block content %}
    <div class='container mt-5'>
        <h1>Title: {{ book.title }}</h1>
        <div class='container mt-5'>
            <p>
                Author: <a href='{{ book.author.get_absolute_url }}'>{{ book.author }}</a>
            </p>
            <p>Summary: {{ book.summary }}</p>
            <p>ISBN: {{ book.isbn }}</p>
            <p>Genre: {{ book.genre.all|join:", " }}</p>
        </div>
    </div>
    {% for copy in book.bookinstance_set.all %}
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
            {{ copy.get_status_display }}
        </p>
        {% if copy.status != 'a' %}
            <p>
                <strong>Due to be returned:</strong> {{ copy.due_back }}
            </p>
        {% endif %}
        <p>
            <strong>Imprint:</strong> {{ copy.imprint }}
        </p>
        <p class="text-muted">
            <strong>Id:</strong> {{ copy.id }}
        </p>
    {% endfor %}
</div>
{% endblock content %}

catalog/templates/catalog/book_list.html
{% extends 'base_generic.html' %}
{% block title %}
    Books List
{% endblock title %}
{% block content %}
    <div class='container mt-5'>
        <h1>Book List</h1>
        {% if book_list %}
            <ul>
                {% for book in book_list %}
                    <li>
                        <a class='book-name' href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                        ({{ book.author }})
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No hay libros para mostrar</p>
        {% endif %}
    </div>
    <p>{{ algun_valor }}</p>
{% endblock content %}

catalog/templates/index.html
{% extends 'base_generic.html' %}
{% block content %}
    <h1 id='index-title'>Local Library Home</h1>
    <p>
        Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!
    </p>
    <h2>Dynamic content</h2>
    <p>The library has the following record counts:</p>
    <ul>
        <li>
            <strong>Books:</strong> {{ num_books }}
        </li>
        <li>
            <strong>Copies:</strong> {{ num_instances }}
        </li>
        <li>
            <strong>Copies available:</strong> {{ num_instances_available }}
        </li>
        <li>
            <strong>Authors:</strong> {{ num_authors }}
        </li>
        <li>
            <strong>Libros que incluyen 'the' en el nombre:</strong> {{ book_include_the }}
        </li>
    </ul>
    {% if num_visits == 0 %}
        <p>Es la primera vez que visitas esta página</p>
    {% else %}
        <p>Visitaste esta página {{ num_visits }} ve{{ num_visits|pluralize:"z,ces" }}</p>
    {% endif %}
{% endblock %}